### ISSUE TITLE
PHP Memory Error in class.dynamic_forms.php

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1707]
on nginx with installed osTicket v1.9.5.1 and get this error when try open ticket:

FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in ..../include/class.dynamic_forms.php on line 1137

i set memmory limit to 512MB and get 
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in ..../include/class.dynamic_forms.php on line 1137

Server info:
nginx 1.7.8 (Linux)
PHP 5.6.5

**Comment by Hamsteren** [comment]
nginx isnt officially supported, you might be better off asking for help on the forum.

**Comment by ntozier** [comment]
He did ask on the forums.  I sent him here.

http://osticket.com/forum/discussion/84739/php-memory-error-in-class-dynamic-forms-php#latest

**Comment by Hamsteren** [comment]
Sorry didn't know that.

**Comment by ntozier** [comment]
No worries. :)

**Comment by infectormp** [comment]
problem in PHP-FPM not in nginx.

**Comment by greezybacon** [comment]
I'd love to get to the bottom of this. I have observed the issue consistently using PHP-FPM — at a different location in the codebase, but haven't stumbled across a solution yet.

**Comment by infectormp** [comment]
look like problem in database. i drop osticket database and install it again. with clean database all work fine.

then i drop clear db and restore "broken" and get same error.

**Comment by rp-tech** [comment]
Mine seems to work fine (so far).

-OSTicket 1.9.5.1
-Debian 7
-Nginx 1.2.1 -> older version, possibly because of Debian 'stable' release cycle (acquired using apt)

What flavor is your linux server? Perhaps the issue is that you are running a newer version of Nginx (more unstable?) I used to run Arch for giggles but never in a production environment!

**Comment by infectormp** [comment]
osTicket work fine if i make clean install of osTicket 1.9.5.1
-Gentoo x64
-nginx 1.9.8
-mariadb 10.0.16

i get this error after update osticket from 1.8.7 to 1.9.5.1. I reprosuce this error after restore 1.8.7 db to 1.9.5.1 instalation.

**Comment by rp-tech** [comment]
Hmm, I'm also running Maria DB 10.0.16 and I updated to NGINX 1.6.2 and it's working as well. On the other hand, I use Debian (not Gentoo).

Coincidentally, I imported my database from 1.9.4 -> 1.9.5 as well but mine works. Possibly database corruption?

**Comment by infectormp** [comment]
i can upload db dump to somewhere. this is test db.

**Comment by greezybacon** [comment]
@infectormp hmm. I wonder if this is a recursion loop. We implemented a fix for a such issue on `develop-next`, 4b5b69d2adce10fa9c5ffdb09c3a8b11d74994f7
```patch
diff --git a/include/class.dynamic_forms.php b/include/class.dynamic_forms.php
index 8baf336..11bb389 100644
--- a/include/class.dynamic_forms.php
+++ b/include/class.dynamic_forms.php
@@ -1154,9 +1154,13 @@ function getField() {
     }
 
     function getValue() {
-        if (!$this->_value && isset($this->value))
+        if (!isset($this->_value) && isset($this->value)) {
+            //XXX: We're settting the value here to avoid infinite loop
+            $this->_value = false;
             $this->_value = $this->getField()->to_php(
                 $this->get('value'), $this->get('value_id'));
+        }
+
         return $this->_value;
     }
 
```

**Comment by infectormp** [comment]
@greezybacon, this is magic! Your fix is work. 

I restore old database, check for error and error still here, apply your patch and MAGIC... ticket open correctly. Fix work.

Restore new database and osTicket sill work with this patch :+1:
