### ISSUE TITLE
organization form: Last Updated value only changes if special fields were updated

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#1997]
When I update an organization the "last updated" value don't change for example when I change (update) the phone number, the address, the website or the internal note of the organization. When I change the name of the organization the last updated value/timestamp will be written. Is this a wanted behavior or a bug? I have tested this with an older version (1.9.4) and the actual version (1.9.7) of osticket. 
This is the value that I'm speaking about:
![osticket organization](https://cloud.githubusercontent.com/assets/5539456/7363303/7d3dd00a-ed78-11e4-9a56-b7657654e901.JPG)

**Comment by greezybacon** [comment]
@mfelber I agree with you, the time of last update should be just that

**Comment by greezybacon** [comment]
I think this is fixed 64fee583cf6df37a836c698424564e36fca8f717

**Comment by mfelber** [comment]
@greezybacon I have tried the fix in both versions but unfortunately it doesn't fix the issue.

In version 1.9.4 I see more problems with the fix: when I edit the street, the phone number or so, the changed values will not be saved. Also the "last updated" date will only be set when the name of the organization changes. But maybe the fix isn't for this version.

In version 1.9.7 The fix doesn't makes additional problems like in version 1.9.4. But also the "last updated" date will only change if the name of the organization changes. 

To apply the patch I have replaced the two files, is that right?

By the way: sometimes I see the following message for one second "you need to select at least one team" when I click on "Update organization". But it doesn't seems to have a negative effect.

**Comment by mfelber** [comment]
In the decription of the fix "custom data" is mentioned. The problematic fields that I mean are no custom fields. They are included in the organization form of osticket. Maybe therefore it doesn't help..

**Comment by greezybacon** [comment]
@mfelber the patch is a *long* way from v1.9.4. I imagine it wouldn't work very well.

In [class.user.php](https://github.com/osTicket/osTicket-1.8/blob/64fee583cf6df37a836c698424564e36fca8f717/include/class.user.php), line 573, you can see the `updated` time is set if updating local fields (such as `name`), and on line 541, the `updated` time is set if any of the related custom data is updated.

I think it should work. I'll leave it open and can make another test after the release of v1.9.8

**Comment by greezybacon** [comment]
Actually, my bad, after I posted that comment, I realize we're talking about two different things — users and organizations

**Comment by greezybacon** [comment]
Ok, so I proposed #2007 which touches the update time for organizations when custom data is updated. I can't replicate the issue with non custom fields on the `develop` branch. Updating the `name` results in the `updated` time being touched as well

**Comment by mfelber** [comment]
That is the point: updating the "name" of an organization works (even in my installations). But updating the "phone number" or the "website" or the "internal note" will not change the "updated time". I have tested this also with the develop branch and with #2007. The same behavior. Only changing the "name" changes the "last updated" date/timestamp..

**Comment by mfelber** [comment]
Hmm, I tried it again with develop branch and #2007 and it works now! Thank you for the fix! I guess I made something wrong the last time I tried it. Sorry for the confusion. It doesn't work with my version 1.9.7 and my german language pack. I will make further tests to see if I can find the reason why the fix doesn't work for this constellation..

**Comment by mfelber** [comment]
Ok, I see why it only works with develop next. This commit https://github.com/osTicket/osTicket-1.8/commit/64fee583cf6df37a836c698424564e36fca8f717 is needed for the patch #2007. It has nothing to do with the language pack. I will close the issue.

**Comment by greezybacon** [comment]
@mfelber thanks for your exhaustive testing!

**Comment by mfelber** [comment]
@greezybacon Anytime.
