### ISSUE TITLE
v1.9.9: %{recipient.ticket_link} wrong formatting after saving changes

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2201]
Hi,
I am trying to create a link to a text by using the variable %{recipient.ticket_link}. System saves the changes but when switching to a different template and then going back to the recent template where the variable was added the system shows the following variable instead: %%7Bticket.staff_link%7D 

The problem is that any variable that I touch gets scrambled like the one above and all the links in the email are unusable.

**Comment by SolidK0RE** [comment]
Got the same problem, My work around is you need to manually edit email templates in the database and add this variable directly in ost_email_template table.

**Comment by C4RLOCO** [comment]
Good advice @SolidK0RE.. I am doing the same thing... most all my email templates are useless at this point.

**Comment by Chefkeks** [comment]
I'm always switching to Html view when email variables get scrumbeld and insert the variable there. Never had a problem that I needed to go further and edit the templates directly in the database. So try html view next time ;)

**Comment by C4RLOCO** [comment]
Hi @Chefkeks, I tried the html view but I don't see any difference... I think is the Text Editor causing the problem...

**Comment by Chefkeks** [comment]
Re-reading this I think it was not 100% clear what I meant with "html view". Just to be clear, I meant the view when you look at the pure html code after hitting the <b> <> </b> button.

And yes I guess it's the text editor that sometimes scrumbeld the links.

**Comment by C4RLOCO** [comment]
@greezybacon any thoughts about this?

**Comment by greezybacon** [comment]
The Redactor editor is having a hard time with the link mangling. I'm thinking I should write my own HTML editor too, I guess

**Comment by Chefkeks** [comment]
@greezybacon
Ambitious goal :+1:

**Comment by greezybacon** [comment]
This is fixed in #2223

**Comment by mlipok** [comment]
It looks that the problem is back:
http://osticket.com/forum/discussion/comment/99682

**Comment by ntozier** [comment]
Have you installed #2223?

**Comment by mlipok** [comment]
I read that #2223 was fixed here
https://github.com/osTicket/osTicket-1.8/releases/tag/v1.9.11

I have installed:
https://github.com/osTicket/osTicket-1.8/releases/tag/v1.9.12

so I can answer to you: Yes.

**Comment by animha** [comment]
Hello, I have the very last version but the bug is still here.
All emails sent by the system have malformed links and are useless.

Please, I'd like to use this tool but at this time I cannot without emails!

**Comment by SpudR** [comment]
Bug still in 1.10 release.
It is the editor the seems to replace the '{' and '}' symbols with their HTML reference (%7B and %7D).
This makes the URLS look like - %%7Burl&7D/login.php - which is obviously wrong.

**Comment by altayevrim** [comment]
The bug still exists. Editor changes links to "%%7 Recipient.ticket _link%7D" whether I use HTML editor or visual editor.

**Comment by shimsim** [comment]
I can confirm that I am also seeing this bug in the current version 1.14.1. 
Using chrome, will try another browser and see if that makes any difference

**Comment by shimsim** [comment]
Have also tested with firefox, no difference and doesn't matter if I work and save in the HTML view. Should be noted that its only changing the { and } when they are wrapped in a link (i.e. `<a href="%{recipient.ticket_link}">` ), all other uses of { and } are not being changed.

**Comment by sevmonster** [comment]
This issue still occurs on latest develop branch.

**Comment by JediKev** [comment]
@ds6 

It doesn't matter if it's `%{recipient.ticket_link}` or `%%7Brecipient.ticket_link%7D` we replace both. See:
https://github.com/osTicket/osTicket/blob/8494308315d08f61d6809f1e0c6bb46299c4ad3b/include/class.variable.php#L30

Cheers.

**Comment by sevmonster** [comment]
@JediKev Thank you. I have noticed however that occasionally links will be empty, which may be a coincidence and not related to this issue; I assumed it was.
![image](https://user-images.githubusercontent.com/16788697/96737185-fdd1e680-1382-11eb-82b8-d21bfb3aef6c.png)
I will continue investigating this issue.

Should this ticket be closed again since it is sidestepped?
